#!/bin/bash

get_realpath_location()
{
	if hash realpath 2>/dev/null; then
		echo $(realpath -s "$1")
	elif hash readlink 2>/dev/null; then
		echo $(readlink -m "$1")
	else
		echo "$1"
	fi
}

gpi="17508755" #git project ID
location=$(dirname $(get_realpath_location "$0"))
file_version="v0.2.21"

wget -q -nv -O \
	"$location/idena-manager" \
	"https://gitlab.com/api/v4/projects/$gpi/repository/files/idena-manager/raw?ref=$file_version"

wget -q -nv -O \
	"$location/idena-manager-autocomplete.bash" \
	"https://gitlab.com/api/v4/projects/$gpi/repository/files/idena-manager-autocomplete.bash/raw?ref=$file_version"

source $(bash $location/idena-manager setup-autocomplete)
bash $location/idena-manager set-user
bash $location/idena-manager cron
chmod +x $location/idena-manager
